Controllers/Alquiler_de_espacioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto1ConLogin.Models;

namespace Proyecto1ConLogin.Controllers
{
    public class Alquiler_de_espacioController : Controller
    {
        private BDEventosEntities db = new BDEventosEntities();

        // GET: Alquiler_de_espacio
        public ActionResult Index()
        {
            var alquiler_de_espacio = db.Alquiler_de_espacio.Include(a => a.Encargado_del_evento).Include(a => a.Show_a_presentar);
            return View(alquiler_de_espacio.ToList());
        }

        // GET: Alquiler_de_espacio/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alquiler_de_espacio alquiler_de_espacio = db.Alquiler_de_espacio.Find(id);
            if (alquiler_de_espacio == null)
            {
                return HttpNotFound();
            }
            return View(alquiler_de_espacio);
        }

        // GET: Alquiler_de_espacio/Create
        public ActionResult Create()
        {
            ViewBag.Encargado = new SelectList(db.Encargado_del_evento, "Encargado", "Nombre_encargado");
            ViewBag.Show = new SelectList(db.Show_a_presentar, "Show", "Nombre_show");
            return View();
        }

        // POST: Alquiler_de_espacio/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Alquiler_evento,Nombre_del_evento,Cantidad_de_asistentes,Fecha_del_evento,Hora_del_evento,Encargado,Show")] Alquiler_de_espacio alquiler_de_espacio)
        {
            if (ModelState.IsValid)
            {
                db.Alquiler_de_espacio.Add(alquiler_de_espacio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Encargado = new SelectList(db.Encargado_del_evento, "Encargado", "Nombre_encargado", alquiler_de_espacio.Encargado);
            ViewBag.Show = new SelectList(db.Show_a_presentar, "Show", "Nombre_show", alquiler_de_espacio.Show);
            return View(alquiler_de_espacio);
        }

        // GET: Alquiler_de_espacio/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alquiler_de_espacio alquiler_de_espacio = db.Alquiler_de_espacio.Find(id);
            if (alquiler_de_espacio == null)
            {
                return HttpNotFound();
            }
            ViewBag.Encargado = new SelectList(db.Encargado_del_evento, "Encargado", "Nombre_encargado", alquiler_de_espacio.Encargado);
            ViewBag.Show = new SelectList(db.Show_a_presentar, "Show", "Nombre_show", alquiler_de_espacio.Show);
            return View(alquiler_de_espacio);
        }

        // POST: Alquiler_de_espacio/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Alquiler_evento,Nombre_del_evento,Cantidad_de_asistentes,Fecha_del_evento,Hora_del_evento,Encargado,Show")] Alquiler_de_espacio alquiler_de_espacio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alquiler_de_espacio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Encargado = new SelectList(db.Encargado_del_evento, "Encargado", "Nombre_encargado", alquiler_de_espacio.Encargado);
            ViewBag.Show = new SelectList(db.Show_a_presentar, "Show", "Nombre_show", alquiler_de_espacio.Show);
            return View(alquiler_de_espacio);
        }

        // GET: Alquiler_de_espacio/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alquiler_de_espacio alquiler_de_espacio = db.Alquiler_de_espacio.Find(id);
            if (alquiler_de_espacio == null)
            {
                return HttpNotFound();
            }
            return View(alquiler_de_espacio);
        }

        // POST: Alquiler_de_espacio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alquiler_de_espacio alquiler_de_espacio = db.Alquiler_de_espacio.Find(id);
            db.Alquiler_de_espacio.Remove(alquiler_de_espacio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/Encargado_del_eventoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto1ConLogin.Models;

namespace Proyecto1ConLogin.Controllers
{
    public class Encargado_del_eventoController : Controller
    {
        private BDEventosEntities db = new BDEventosEntities();

        // GET: Encargado_del_evento
        public ActionResult Index()
        {
            return View(db.Encargado_del_evento.ToList());
        }

        // GET: Encargado_del_evento/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encargado_del_evento encargado_del_evento = db.Encargado_del_evento.Find(id);
            if (encargado_del_evento == null)
            {
                return HttpNotFound();
            }
            return View(encargado_del_evento);
        }

        // GET: Encargado_del_evento/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Encargado_del_evento/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Encargado,Nombre_encargado,Telefono_contacto,Correo_electronico")] Encargado_del_evento encargado_del_evento)
        {
            if (ModelState.IsValid)
            {
                db.Encargado_del_evento.Add(encargado_del_evento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(encargado_del_evento);
        }

        // GET: Encargado_del_evento/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encargado_del_evento encargado_del_evento = db.Encargado_del_evento.Find(id);
            if (encargado_del_evento == null)
            {
                return HttpNotFound();
            }
            return View(encargado_del_evento);
        }

        // POST: Encargado_del_evento/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Encargado,Nombre_encargado,Telefono_contacto,Correo_electronico")] Encargado_del_evento encargado_del_evento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(encargado_del_evento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(encargado_del_evento);
        }

        // GET: Encargado_del_evento/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encargado_del_evento encargado_del_evento = db.Encargado_del_evento.Find(id);
            if (encargado_del_evento == null)
            {
                return HttpNotFound();
            }
            return View(encargado_del_evento);
        }

        // POST: Encargado_del_evento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Encargado_del_evento encargado_del_evento = db.Encargado_del_evento.Find(id);
            db.Encargado_del_evento.Remove(encargado_del_evento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/Show_a_presentarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto1ConLogin.Models;

namespace Proyecto1ConLogin.Controllers
{
    public class Show_a_presentarController : Controller
    {
        private BDEventosEntities db = new BDEventosEntities();

        // GET: Show_a_presentar
        public ActionResult Index()
        {
            var show_a_presentar = db.Show_a_presentar.Include(s => s.Tipo_de_show_a_presentar);
            return View(show_a_presentar.ToList());
        }

        // GET: Show_a_presentar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Show_a_presentar show_a_presentar = db.Show_a_presentar.Find(id);
            if (show_a_presentar == null)
            {
                return HttpNotFound();
            }
            return View(show_a_presentar);
        }

        // GET: Show_a_presentar/Create
        public ActionResult Create()
        {
            ViewBag.Tipo_show = new SelectList(db.Tipo_de_show_a_presentar, "Tipo_show", "Nombre_tipo");
            return View();
        }

        // POST: Show_a_presentar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Show,Nombre_show,Descripcion,Costo_por_hora,Tipo_show")] Show_a_presentar show_a_presentar)
        {
            if (ModelState.IsValid)
            {
                db.Show_a_presentar.Add(show_a_presentar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Tipo_show = new SelectList(db.Tipo_de_show_a_presentar, "Tipo_show", "Nombre_tipo", show_a_presentar.Tipo_show);
            return View(show_a_presentar);
        }

        // GET: Show_a_presentar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Show_a_presentar show_a_presentar = db.Show_a_presentar.Find(id);
            if (show_a_presentar == null)
            {
                return HttpNotFound();
            }
            ViewBag.Tipo_show = new SelectList(db.Tipo_de_show_a_presentar, "Tipo_show", "Nombre_tipo", show_a_presentar.Tipo_show);
            return View(show_a_presentar);
        }

        // POST: Show_a_presentar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Show,Nombre_show,Descripcion,Costo_por_hora,Tipo_show")] Show_a_presentar show_a_presentar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(show_a_presentar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Tipo_show = new SelectList(db.Tipo_de_show_a_presentar, "Tipo_show", "Nombre_tipo", show_a_presentar.Tipo_show);
            return View(show_a_presentar);
        }

        // GET: Show_a_presentar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Show_a_presentar show_a_presentar = db.Show_a_presentar.Find(id);
            if (show_a_presentar == null)
            {
                return HttpNotFound();
            }
            return View(show_a_presentar);
        }

        // POST: Show_a_presentar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Show_a_presentar show_a_presentar = db.Show_a_presentar.Find(id);
            db.Show_a_presentar.Remove(show_a_presentar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Tipo_de_show_a_presentar1/Create.cshtml
@model Proyecto1ConLogin.Models.Tipo_de_show_a_presentar

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tipo_de_show_a_presentar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion_tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion_tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion_tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Tipo_de_show_a_presentar1/Delete.cshtml
@model Proyecto1ConLogin.Models.Tipo_de_show_a_presentar

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tipo_de_show_a_presentar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre_tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion_tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion_tipo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Tipo_de_show_a_presentar1/Details.cshtml
@model Proyecto1ConLogin.Models.Tipo_de_show_a_presentar

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tipo_de_show_a_presentar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre_tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion_tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion_tipo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Tipo_show }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Tipo_de_show_a_presentar1/Edit.cshtml
@model Proyecto1ConLogin.Models.Tipo_de_show_a_presentar

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tipo_de_show_a_presentar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Tipo_show)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion_tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion_tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion_tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Tipo_de_show_a_presentar1/Index.cshtml
@model IEnumerable<Proyecto1ConLogin.Models.Tipo_de_show_a_presentar>

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Empresa All Stars</h1>
    <p class="lead">Control de Alquileres</p>
</div>

<div class="row">
    <div class="col-md-6">
        @Html.ActionLink("Tipo de show a presentar", "Index", "Tipo_de_show_a_presentar")
        <img src="https://www.showlive.mx/images/logo_showlive_lg.png" width="550px" />
    </div>

    <div class="col-md-6">
        @Html.ActionLink("Encargados de eventos", "Index", "Encargado_del_evento")
        <img src="https://img.genial.ly/5e35a10e154b0c0f95944bd3/b2a2e84f-8213-4d91-a41f-0d9476a203aa.png" width="550px" />
    </div>

    <div class="col-md-6">
        @Html.ActionLink("Shows", "Index", "Show_a_presentar")
        <img src="https://thehouserecords.com/wp-content/uploads/2022/01/Elementos-de-la-musica.png" width="550px" />
    </div>

    <div class="col-md-6">
        @Html.ActionLink("Alquiler de espacio", "Index", "Alquiler_de_espacio")
        <img src="https://images.vexels.com/media/users/3/274206/isolated/preview/7557be176f7049d81e04a4fb94dbee63-campo-de-paisaje-natural-con-el-sol-plano.png" width="550px" />
    </div>
</div>